### ISSUE TITLE
🗺️ Roadmap

### ISSUE THREAD

**Issue by axieax** [axieax/urlview.nvim#3]
Plan for future features:

- [ ] vimdocs (auto docgen like [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim/blob/master/scripts/gendocs.lua)?
- [ ] Use a general URL pattern (captures both http prefix and www prefix, can detect more general urls without www prefix such as example.com)
- [ ] Search multiple files (e.g. in project, open buffers)
- [ ] Config validation (`validation.ctx`, `validation.config`, `validation.helpers`, type unions, `vim.validate`)
- [ ] Combine search and validation (return a table containing both instead)
- [ ] Windows support with `start` (and WSL?)
- [ ] Command completion for `picker` and `action`
- [ ] Add GIFs for README demos

Completed features:

<details>
<summary>Show completed</summary>

- [x] Add Plenary tests for content search
- [x] Alternative pickers (Telescope integration) #4 
- [x] packer.nvim urls #2 
- [x] Extensible search contexts (e.g. Jira links) #12
- [x] Add GitHub action for test runner, code formatter and linter #14
- [x] Improve `UrlView` command completion for `opts` + `opts` validation #24
- [x] vim-plug urls #26 
- [x] Sort (strategies: same order in buffer, alphabetical, etc.) and unique options #29 
- [x] Jump to prev / next URL in buffer #33

</details>

**Comment by axieax** [comment]
Closed so it doesn't show up as an open issue
